### ISSUE TITLE
Variable 'length' referenced before assignment

### ISSUE THREAD

**Issue by fkollingiv** [KCCG/rageseq#4]
Hello, 

I'm working my way through the early steps of the pipeline and can't get past the rageMatch.py script. I am receiving the following error: UnboundLocalError: local variable 'length' referenced before assignment

Here is the command:  python ~/rageseq-master/rageMatch.py -q ../Dartmouth-RAGESeq-Nanopoe-LSK110-8242021/fastq_pass/rage.fastq.gz -o ./ -b transformed-bc.tsv --length 200 -t 10 -f 250 -n 1

Any help is greatly appreciated.

**Comment by fkollingiv** [comment]
I probably should have included the error as well:

Traceback (most recent call last):
  File "/dartfs-hpc/rc/home/j/f00331j/rageseq-master/rageMatch.py", line 129, in <module>
    main()
  File "/dartfs-hpc/rc/home/j/f00331j/rageseq-master/rageMatch.py", line 79, in main
    do_batch(args, fq_list, bcs, out)
  File "/dartfs-hpc/rc/home/j/f00331j/rageseq-master/rageMatch.py", line 95, in do_batch
    k = re.search(bc[2], fq[1][:length])
UnboundLocalError: local variable 'length' referenced before assignment

**Comment by Psy-Fer** [comment]
Hello,

Please do a `git clone` to the the small bug fix I just did on rageMatch.py to fix this issue.
Sorry about that. Our internal version of these scripts has been totally re-written, so I didn't catch this bug. 

Cheers,
James
